# Generated by Django 4.1.3 on 2022-11-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.TextField(max_length=100)),
                ('blog_date', models.DateTimeField()),
                ('blog_text', models.CharField(max_length=300)),
                ('blog_image', models.ImageField(upload_to='blog_images')),
            ],
        ),
    ]
